#ifdef __OBJC__
#import <UIKit/UIKit.h>
#else
#ifndef FOUNDATION_EXPORT
#if defined(__cplusplus)
#define FOUNDATION_EXPORT extern "C"
#else
#define FOUNDATION_EXPORT extern
#endif
#endif
#endif

#import "BITActivityIndicatorButton.h"
#import "BITApplication.h"
#import "BITAppStoreHeader.h"
#import "BITAppVersionMetaInfo.h"
#import "BITArrowImageAnnotation.h"
#import "BITAttributedLabel.h"
#import "BITAuthenticationViewController.h"
#import "BITAuthenticator.h"
#import "BITBase.h"
#import "BITBlurImageAnnotation.h"
#import "BITCategoryContainer.h"
#import "BITChannel.h"
#import "BITCrashAttachment.h"
#import "BITCrashCXXExceptionHandler.h"
#import "BITCrashDetails.h"
#import "BITCrashManager.h"
#import "BITCrashManagerDelegate.h"
#import "BITCrashMetaData.h"
#import "BITCrashReportTextFormatter.h"
#import "BITData.h"
#import "BITDevice.h"
#import "BITDomain.h"
#import "BITEnvelope.h"
#import "BITEventData.h"
#import "BITFeedbackActivity.h"
#import "BITFeedbackComposeViewController.h"
#import "BITFeedbackComposeViewControllerDelegate.h"
#import "BITFeedbackListViewCell.h"
#import "BITFeedbackListViewController.h"
#import "BITFeedbackManager.h"
#import "BITFeedbackManagerDelegate.h"
#import "BITFeedbackMessage.h"
#import "BITFeedbackMessageAttachment.h"
#import "BITFeedbackUserDataViewController.h"
#import "BITGZIP.h"
#import "BITHockeyAppClient.h"
#import "BITHockeyAttachment.h"
#import "BITHockeyBaseManager.h"
#import "BITHockeyBaseViewController.h"
#import "BITHockeyHelper.h"
#import "BITHockeyLogger.h"
#import "BITHockeyManager.h"
#import "BITHockeyManagerDelegate.h"
#import "BITHTTPOperation.h"
#import "BITImageAnnotation.h"
#import "BITImageAnnotationViewController.h"
#import "BITInternal.h"
#import "BITKeychainUtils.h"
#import "BITMetricsManager.h"
#import "BITPersistence.h"
#import "BITRectangleImageAnnotation.h"
#import "BITSender.h"
#import "BITSession.h"
#import "BITSessionState.h"
#import "BITSessionStateData.h"
#import "BITStoreButton.h"
#import "BITStoreUpdateManager.h"
#import "BITStoreUpdateManagerDelegate.h"
#import "BITTelemetryContext.h"
#import "BITTelemetryData.h"
#import "BITTelemetryObject.h"
#import "BITUpdateManager.h"
#import "BITUpdateManagerDelegate.h"
#import "BITUpdateViewController.h"
#import "BITUser.h"
#import "BITWebTableViewCell.h"
#import "HockeySDK.h"
#import "HockeySDKEnums.h"
#import "HockeySDKFeatureConfig.h"
#import "HockeySDKFeatureConfig_CP.h"
#import "HockeySDKNullability.h"

FOUNDATION_EXPORT double HockeySDK_SourceVersionNumber;
FOUNDATION_EXPORT const unsigned char HockeySDK_SourceVersionString[];

