#import <UIKit/UIKit.h>

#import "BITActivityIndicatorButton.h"
#import "BITAppStoreHeader.h"
#import "BITAppVersionMetaInfo.h"
#import "BITArrowImageAnnotation.h"
#import "BITAttributedLabel.h"
#import "BITAuthenticationViewController.h"
#import "BITAuthenticator.h"
#import "BITBlurImageAnnotation.h"
#import "BITCrashAttachment.h"
#import "BITCrashCXXExceptionHandler.h"
#import "BITCrashDetails.h"
#import "BITCrashManager.h"
#import "BITCrashManagerDelegate.h"
#import "BITCrashMetaData.h"
#import "BITCrashReportTextFormatter.h"
#import "BITFeedbackActivity.h"
#import "BITFeedbackComposeViewController.h"
#import "BITFeedbackComposeViewControllerDelegate.h"
#import "BITFeedbackListViewCell.h"
#import "BITFeedbackListViewController.h"
#import "BITFeedbackManager.h"
#import "BITFeedbackManagerDelegate.h"
#import "BITFeedbackMessage.h"
#import "BITFeedbackMessageAttachment.h"
#import "BITFeedbackUserDataViewController.h"
#import "BITHockeyAppClient.h"
#import "BITHockeyAttachment.h"
#import "BITHockeyBaseManager.h"
#import "BITHockeyBaseViewController.h"
#import "BITHockeyHelper.h"
#import "BITHockeyManager.h"
#import "BITHockeyManagerDelegate.h"
#import "BITHTTPOperation.h"
#import "BITImageAnnotation.h"
#import "BITImageAnnotationViewController.h"
#import "BITKeychainUtils.h"
#import "BITRectangleImageAnnotation.h"
#import "BITStoreButton.h"
#import "BITStoreUpdateManager.h"
#import "BITStoreUpdateManagerDelegate.h"
#import "BITUpdateManager.h"
#import "BITUpdateManagerDelegate.h"
#import "BITUpdateViewController.h"
#import "BITWebTableViewCell.h"
#import "HockeySDK.h"
#import "HockeySDKEnums.h"
#import "HockeySDKFeatureConfig.h"
#import "HockeySDKFeatureConfig_CP.h"
#import "HockeySDKNullability.h"

FOUNDATION_EXPORT double HockeySDK_SourceVersionNumber;
FOUNDATION_EXPORT const unsigned char HockeySDK_SourceVersionString[];

